### ISSUE TITLE
Example or Blog post

### ISSUE THREAD

**Issue by AhmadEl-Banna** [kennetpostigo/react-reach#1]
is there any example or blog post to get start with react-reach ?

**Comment by kennetpostigo** [comment]
Hey, @AhmadEl-Banna at the moment I haven't had enough time to get a blog post going. Though the examples in the `readme` should get you up and running or at least an idea of how to get things rolling with plugging it in to a project. If there is anything that you don't understand please let me know so that I can add examples of it to the `readme` to detail it. Thank you for reaching out.

**Comment by mtsewrs** [comment]
You need to add some examples. How do I get the data to my component?

**Comment by kennetpostigo** [comment]
@mattiasewers @AhmadEl-Banna I've gone in and added a more thorough example in the readme. Please check it out and let me know if it clears things up.

If it does feel free to close the issue. If not than make sure to `@kennetpostigo` so I get an notification.
